# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.5.0
        enviroment: 
          PGHOST: localhost
          PGUSER: quantified_self
          NODE_ENV: test

      - image: postgres:11.3
        environment:
          POSTGRES_USER: quantified_self
          POSTGRES_DB: quantified_self_test
          POSTGRES_PASSWORD: ''
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/quantified_self

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npx sequelize db:drop
      - run: npx sequelize db:create
      - run: npx sequelize db:migrate


      # run tests!
      - run: npm test


